In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
os.chdir("C://Users//opc//2021//NG")

In [3]:
df_analyse = pd.read_csv("df_analyse_02APR2021.csv")

In [3]:
df_new = pd.read_csv("NG_new.csv")

In [4]:
df_old = pd.read_csv("NG_Old.csv")

In [5]:
df_old

,COUNTRY_ID,SYSTEM,VENDOR,ITEM,NEW_UPC,OLD_UPC,NEW_DESC,OLD_DESC,NEW_GEN,OLD_GEN,NEW_CREATE_DATE,OLD_CREATE_DATE,NEW_KEYCAT,OLD_KEYCAT,NEW_BRAND_ID,OLD_BRAND_ID
0,1,8,14602,245,8011460200245,8011460200245,KENTUCKYS BEST LT 100 BOX PACK,KENTUCKY BEST GOLDBX100FS/CT EACH,1,1,14-JAN-21,24-JUN-10,7606,7606,349197,349197
1,1,8,14602,245,8011460200245,8011460200245,KENTUCKYS BEST LT 100 BOX PACK,KENTUCKY BEST GLD100BX FS/CT EACH,1,1,14-JAN-21,08-JAN-11,7606,7606,349197,349197
2,1,8,14602,245,8011460200245,8011460200245,Kentuckys Best Gold 100 Box Pk,KENTUCKYS BEST LT BOX 100 MM P,1,1,12-JAN-21,02-JUL-20,7606,7606,349197,349197
3,1,8,14602,245,8011460200245,8011460200245,Kentuckys Best Gold 100 Box Pk,KENTUCKY BEST L 100 BXLIP/CT EACH,1,1,12-JAN-21,14-MAY-08,7606,7606,349197,349197
4,1,8,14602,245,8011460200245,8011460200245,Kentuckys Best Gold 100 Box Pk,KBSLG CIG LT 100LG NMNTL BX 1C020CT,1,1,12-JAN-21,02-AUG-17,7606,7606,349197,349197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494367,118448,93,51328,15,93015132800015,93015132800015,GIPPSLAND JERSEY SOUR CREAM 300ML,GIPPSLAND JERSEY SOUR CREAM 300ML,1,1,08-JAN-21,26-OCT-20,269,269,1835171,1835171
2494368,118448,93,54849,276,93015484900276,93015484900276,Y/FOODZ ICED COFFEE SHOT 100ML,YOUFOODZ ICED COFFEE SHOT 100ML,1,1,13-JAN-21,26-OCT-20,198,198,1826714,1826714
2494369,118448,93,30141,668,93013014100668,93013014100668,MACS BUTTER SHORTBREAD TRAD 325G,MACS BSCT S/BRD BUTTER 325G,1,1,08-JAN-21,21-DEC-20,246,246,1861124,1861124
2494370,118448,97,81624,14368,97018162414368,97018162414368,ADULT COLOURING BOOK 1,ST MARTINS PRESS COLOURING BOOK THAILAND,1,1,08-JAN-21,26-OCT-20,191,191,2057833,2057833
2494371,118448,93,51914,98459,93015191498459,93015191498459,"BB BASIC BIKINI ., BLACK, 10",BRILLIANT BASICS WOMENS BIKINI BRIEF BLACK 10 1PK,1,1,08-JAN-21,21-DEC-20,264,264,1885301,1885301

In [7]:
#df_new[['SYSTEM','VENDOR','ITEM','DESC_BANK_ITEM_NAME']].groupby(['SYSTEM','VENDOR','ITEM'],as_index=False)['DESC_BANK_ITEM_NAME'].transform(lambda x: ' '.join(x)).drop_duplicates(keep='first')

In [8]:
df_new['SVI'] = df_new['SYSTEM'].astype(str) + "-" +  df_new['VENDOR'].astype(str) + "-" +  df_new['ITEM'].astype(str)

In [9]:
#df_new[['SYSTEM','VENDOR','ITEM','DESC_BANK_ITEM_NAME']].groupby(['SYSTEM','VENDOR','ITEM'],as_index=True)['DESC_BANK_ITEM_NAME'].transform(lambda x: ' '.join(x)).drop_duplicates(keep='first')
#df_new[['SYSTEM','VENDOR','ITEM','DESC_BANK_ITEM_NAME']].groupby(['SYSTEM','VENDOR','ITEM'],as_index=True)['DESC_BANK_ITEM_NAME'].transform(lambda x: ' '.join(x)).drop_duplicates(keep='first')
#df_new[['SYSTEM','VENDOR','ITEM','SVI','DESC_BANK_ITEM_NAME']].head(100).groupby(['SVI'],as_index=True)['DESC_BANK_ITEM_NAME'].transform(lambda x: ' '.join(x)).drop_duplicates(keep='first')
df_new_grpd = df_new[['SYSTEM','VENDOR','ITEM','SVI','DESC_BANK_ITEM_NAME']].groupby(['SVI'])['DESC_BANK_ITEM_NAME'].apply(' '.join).reset_index()

In [10]:
df_new_grpd

                   SVI                                DESC_BANK_ITEM_NAME
0            0-1-30569                    NOT ON RP AT TIME OF SALE     1
1             0-1-5574                             CCDM FREE CHIC SAND CM
2             0-1-5575                             CCDM FREE CHIC SAND CM
3            0-1-65903                 TROLLI SR BR OCTPS            6.3Z
4            0-1-70912                  BATISTE DARK SH               10Z
...                ...                                                ...
287334  98-70002-80325                      # BARRA INTEGRAL 240 GR.|||||
287335  98-70406-89743                 NZ SPRINGS WATER SIPPER CAP 1.25LT
287336   98-75123-1300                         DIAMOND GOLD RICE PAPER 37
287337   98-75123-1321                           DIAMOND RICE PAPER 375GM
287338   98-88458-1578  2L HOT WATER BOTTLE EA HOT WATER BOTTLE 2LT L/...

[287339 rows x 2 columns]

In [11]:
df_old = df_old[~(df_old['OLD_DESC'].isnull())]

In [12]:
df_old['OLD_DESC'] = df_old['OLD_DESC'].astype(str)

<ipython-input-12-a9af8672f496>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_old['OLD_DESC'] = df_old['OLD_DESC'].astype(str)

In [13]:
df_old['SVI'] = df_old['SYSTEM'].astype(str) + "-" +  df_old['VENDOR'].astype(str) + "-" +  df_old['ITEM'].astype(str)

<ipython-input-13-92e23d05e972>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_old['SVI'] = df_old['SYSTEM'].astype(str) + "-" +  df_old['VENDOR'].astype(str) + "-" +  df_old['ITEM'].astype(str)

In [14]:
df_old_grpd = df_old[['COUNTRY_ID','OLD_KEYCAT','OLD_BRAND_ID','SYSTEM','VENDOR','ITEM','SVI','OLD_DESC']].groupby(['COUNTRY_ID','OLD_KEYCAT','OLD_BRAND_ID','SVI'])['OLD_DESC'].apply(' '.join).reset_index()
df_new_grpd = df_new[['COUNTRY_LOCATION_ID','KEYCAT_ID','BRAND_ID','SYSTEM','VENDOR','ITEM','SVI','DESC_BANK_ITEM_NAME']].groupby(['COUNTRY_LOCATION_ID','KEYCAT_ID','BRAND_ID','SVI'])['DESC_BANK_ITEM_NAME'].apply(' '.join).reset_index()

In [15]:
df_new_grpd

,COUNTRY_LOCATION_ID,KEYCAT_ID,BRAND_ID,SVI,DESC_BANK_ITEM_NAME
0,1,102,42440,0-15000-4771,"GERBER YOGURT BLENDS, MIXED BERRY,"
1,1,102,42440,0-15000-4879,GB PS VEG/CHKN/RICE 7.3 OZ
2,1,102,42440,27-716-58046,GERBER FF 1.48OZ FRT PUFF STRWAP
3,1,102,42523,0-15000-4436,GB2 NAT PARAPPGING POUCH
4,1,102,43232,0-15000-25106,GERBER MEAL BOWL GRDN TOMATO 4.5 OZ
...,...,...,...,...,...
288034,118448,269,2019637,94-21903-48629,ROLLS WHOLEMEAL 6PK
288035,118448,270,1887281,0-950-7755,KODAK CMRA BUDGET 27EXP
288036,118448,270,1887281,27-1504-106,KODAK FUNSAVER AND FLASH 27EXP
288037,118448,270,1887281,76-2151-150,KODAK CAMERA MAX O/DOOR 39EXP 1 S
288038,118448,270,2005966,93-14700-24207,DIGITRON 24 EXP FLASH CAMR

In [16]:
df_old_grpd

,COUNTRY_ID,OLD_KEYCAT,OLD_BRAND_ID,SVI,OLD_DESC
0,1,102,8387,0-52200-576,BEECHNUT STAGE 2 CORN & SWEET POTATO 4OZ BN ST...
1,1,102,8387,0-52200-714,"BEECH-NUT CLASSICS BABY FOOD, STAGE 2, T BN ST..."
2,1,102,42440,0-15000-4771,GERBER YOGURT BLENDS MIXED BERRY 4CT 3.5 GERBE...
3,1,102,42440,0-15000-4879,GERB GRAD ENTR VG/CHKN/RC 6 Z ZOZZZL GERGR...
4,1,102,42440,27-716-58046,GERBER 1.48OZ FRT PUFF STRWAP GERBER FF ...
...,...,...,...,...,...
278456,118448,270,1969855,76-5578-143,TRANSCEND MMRY CRD SD 2GB 1PK
278457,118448,270,1969855,76-5578-191,MINI SD CARD 1GB TRANSCEND MINI SD CARD 1GB TR...
278458,118448,270,1969855,76-5578-552,TRANSCEND MICRO SD 2GB 1PK TRANSCEND MICRO SD ...
278459,118448,270,1988829,27-1615-649,KODAK GB FILM 200 SPEED 24 EXP 1 PACK **KODAK ...
278460,118448,270,2005966,93-14700-24207,DIGITRON 35MM FLASH CAMERA DIGITRON CAMERA W/F...

In [17]:
df_new_grpd.columns

Index(['COUNTRY_LOCATION_ID', 'KEYCAT_ID', 'BRAND_ID', 'SVI',
       'DESC_BANK_ITEM_NAME'],
      dtype='object')

In [18]:
df_old_grpd = df_old_grpd.rename(columns={'COUNTRY_ID':'COUNTRY_ID_OLD', 'OLD_KEYCAT':'KEYCAT_ID_OLD', 'OLD_BRAND_ID':'BRAND_ID_OLD','OLD_DESC':'DESC_BANK_ITEM_NAME'})
df_old_grpd = df_old_grpd.rename(columns={'DESC_BANK_ITEM_NAME':'DESC_BANK_ITEM_OLD'})
df_old_grpd

,COUNTRY_ID_OLD,KEYCAT_ID_OLD,BRAND_ID_OLD,SVI,DESC_BANK_ITEM_OLD
0,1,102,8387,0-52200-576,BEECHNUT STAGE 2 CORN & SWEET POTATO 4OZ BN ST...
1,1,102,8387,0-52200-714,"BEECH-NUT CLASSICS BABY FOOD, STAGE 2, T BN ST..."
2,1,102,42440,0-15000-4771,GERBER YOGURT BLENDS MIXED BERRY 4CT 3.5 GERBE...
3,1,102,42440,0-15000-4879,GERB GRAD ENTR VG/CHKN/RC 6 Z ZOZZZL GERGR...
4,1,102,42440,27-716-58046,GERBER 1.48OZ FRT PUFF STRWAP GERBER FF ...
...,...,...,...,...,...
278456,118448,270,1969855,76-5578-143,TRANSCEND MMRY CRD SD 2GB 1PK
278457,118448,270,1969855,76-5578-191,MINI SD CARD 1GB TRANSCEND MINI SD CARD 1GB TR...
278458,118448,270,1969855,76-5578-552,TRANSCEND MICRO SD 2GB 1PK TRANSCEND MICRO SD ...
278459,118448,270,1988829,27-1615-649,KODAK GB FILM 200 SPEED 24 EXP 1 PACK **KODAK ...
278460,118448,270,2005966,93-14700-24207,DIGITRON 35MM FLASH CAMERA DIGITRON CAMERA W/F...

In [19]:
df_analyse = df_old_grpd.merge(df_new_grpd,left_on=['COUNTRY_ID_OLD','SVI'],
                 right_on=['COUNTRY_LOCATION_ID','SVI'],how='inner')

In [33]:
df_analyse.head(5)

,COUNTRY_ID_OLD,KEYCAT_ID_OLD,BRAND_ID_OLD,SVI,DESC_BANK_ITEM_OLD,COUNTRY_LOCATION_ID,KEYCAT_ID,BRAND_ID,DESC_BANK_ITEM_NAME
0,1,102,8387,0-52200-576,BEECHNUT STAGE 2 CORN & SWEET POTATO 4OZ BN ST...,1,102,1544051,BEECHNUT STAGE 2 CORN&SWEET POTATO 4 OZ
1,1,102,1544051,0-52200-576,"BEECH-NUT BABY FOOD, CORN & SWEET POTATOES, ST...",1,102,1544051,BEECHNUT STAGE 2 CORN&SWEET POTATO 4 OZ
2,1,102,8387,0-52200-714,"BEECH-NUT CLASSICS BABY FOOD, STAGE 2, T BN ST...",1,102,1544051,BNUT S2 SWEET CARROTS4Z 0004.000
3,1,102,1544051,0-52200-714,B NUT STG 2 CARROTS 4 OZ BN STG...,1,102,1544051,BNUT S2 SWEET CARROTS4Z 0004.000
4,1,102,42440,0-15000-4771,GERBER YOGURT BLENDS MIXED BERRY 4CT 3.5 GERBE...,1,102,42440,"GERBER YOGURT BLENDS, MIXED BERRY,"

In [34]:
dfx = pd.read_csv("Combined_Desc_Data.csv")

In [38]:
dfx.TARGET.value_counts(normalize=True)

0    0.986961
1    0.013039
Name: TARGET, dtype: float64

In [39]:
dfx.head(3)

,COUNTRY_ID_OLD,SVI,KEYCAT_ID_OLD,BRAND_ID_OLD,KEYCAT_ID,BRAND_ID,DESC_BANK_ITEM_OLD,DESC_BANK_ITEM_NAME,NEW_DESC_DIFF,OLD_DISC_DIFF,NEW_TOK_DIF,OLD_TOK_DIF,TOT_NEW_TOKENS,TARGET
0,1,0-52200-576,102,8387,102,1544051,BEECHNUT STAGE 2 CORN & SWEET POTATO 4OZ BN ST...,BEECHNUT STAGE 2 CORN&SWEET POTATO 4 OZ,OZ,4.0OZ BN S2 HMSTYL P B N SWPT POTO BCH NUT PO...,1,24,8,1
1,1,0-52200-576,102,8387,102,1544051,BEECHNUT STAGE 2 CORN & SWEET POTATO 4OZ BN ST...,BEECHNUT STAGE 2 CORN&SWEET POTATO 4 OZ,BEECHNUT POTATO,BEECH NUT BABY FOOD POTATOES NATURALS CLASSIC...,2,12,8,1
2,1,0-52200-576,102,1544051,102,1544051,"BEECH-NUT BABY FOOD, CORN & SWEET POTATOES, ST...",BEECHNUT STAGE 2 CORN&SWEET POTATO 4 OZ,OZ,4.0OZ BN S2 HMSTYL P B N SWPT POTO BCH NUT PO...,1,24,8,0

In [40]:
dfx[dfx['SVI']=='0-52200-576']

,COUNTRY_ID_OLD,SVI,KEYCAT_ID_OLD,BRAND_ID_OLD,KEYCAT_ID,BRAND_ID,DESC_BANK_ITEM_OLD,DESC_BANK_ITEM_NAME,NEW_DESC_DIFF,OLD_DISC_DIFF,NEW_TOK_DIF,OLD_TOK_DIF,TOT_NEW_TOKENS,TARGET
0,1,0-52200-576,102,8387,102,1544051,BEECHNUT STAGE 2 CORN & SWEET POTATO 4OZ BN ST...,BEECHNUT STAGE 2 CORN&SWEET POTATO 4 OZ,OZ,4.0OZ BN S2 HMSTYL P B N SWPT POTO BCH NUT PO...,1,24,8,1
1,1,0-52200-576,102,8387,102,1544051,BEECHNUT STAGE 2 CORN & SWEET POTATO 4OZ BN ST...,BEECHNUT STAGE 2 CORN&SWEET POTATO 4 OZ,BEECHNUT POTATO,BEECH NUT BABY FOOD POTATOES NATURALS CLASSIC...,2,12,8,1
2,1,0-52200-576,102,1544051,102,1544051,"BEECH-NUT BABY FOOD, CORN & SWEET POTATOES, ST...",BEECHNUT STAGE 2 CORN&SWEET POTATO 4 OZ,OZ,4.0OZ BN S2 HMSTYL P B N SWPT POTO BCH NUT PO...,1,24,8,0
3,1,0-52200-576,102,1544051,102,1544051,"BEECH-NUT BABY FOOD, CORN & SWEET POTATOES, ST...",BEECHNUT STAGE 2 CORN&SWEET POTATO 4 OZ,BEECHNUT POTATO,BEECH NUT BABY FOOD POTATOES NATURALS CLASSIC...,2,12,8,0

In [41]:
dfx.shape

(281539, 14)

In [42]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.0.0-cp36-cp36m-win_amd64.whl (23.8 MB)
Collecting smart-open>=1.8.1
  Downloading smart_open-5.0.0-py3-none-any.whl (56 kB)
Requirement already satisfied: numpy>=1.11.3 in c:\programdata\anaconda3\envs\ng\lib\site-packages (from gensim) (1.19.5)
Requirement already satisfied: scipy>=0.18.1 in c:\programdata\anaconda3\envs\ng\lib\site-packages (from gensim) (1.5.4)
Collecting Cython==0.29.21
  Downloading Cython-0.29.21-cp36-cp36m-win_amd64.whl (1.6 MB)
Collecting dataclasses
  Downloading dataclasses-0.8-py3-none-any.whl (19 kB)
Installing collected packages: smart-open, dataclasses, Cython, gensim
Successfully installed Cython-0.29.21 dataclasses-0.8 gensim-4.0.0 smart-open-5.0.0

In [44]:
print(gensim.__version__)

4.0.0

In [52]:
#df_analyse.to_csv("df_analyse.csv",index=False)

In [3]:
df_analyse = pd.read_csv("df_analyse.csv")
df_analyse

,COUNTRY_LOCATION_ID,KEYCAT_ID,BRAND_ID,SVI,DESC_BANK_ITEM_OLD,DESC_BANK_ITEM_NAME
0,1,102,42440,0-15000-4771,GERBER YOGURT BLENDS MIXED BERRY 4CT 3.5 GERBE...,"GERBER YOGURT BLENDS, MIXED BERRY,"
1,1,102,42440,0-15000-4879,GERB GRAD ENTR VG/CHKN/RC 6 Z ZOZZZL GERGR...,GB PS VEG/CHKN/RICE 7.3 OZ
2,1,102,42440,27-716-58046,GERBER 1.48OZ FRT PUFF STRWAP GERBER FF ...,GERBER FF 1.48OZ FRT PUFF STRWAP
3,1,102,43232,0-15000-25106,GERBER HARV BOWL GARDN TOMTO00004.50 GERB ME...,GERBER MEAL BOWL GRDN TOMATO 4.5 OZ
4,1,102,43232,0-15000-301,GERBER PUREES 1ST FOODS PRUNE BABY FOOD GERBER...,GERBER BABY FOOD 1ST FOODS PRU5 OZ
...,...,...,...,...,...,...
276337,118448,269,2019637,94-21903-48629,HARVEST PREMIUM SOY MILK POWDER 400G,ROLLS WHOLEMEAL 6PK
276338,118448,270,1887281,0-950-7755,KODAK CAMERA WITH FLASH 27EXP KODAK CAMERA FLA...,KODAK CMRA BUDGET 27EXP
276339,118448,270,1887281,27-1504-106,KODAK CAMERA FUNSAVER 1PK KODAK CAMERA FUNSAVE...,KODAK FUNSAVER AND FLASH 27EXP
276340,118448,270,1887281,76-2151-150,NO DESC KODAK SGL USE FLSH CAMERA KODAK CAMERA...,KODAK CAMERA MAX O/DOOR 39EXP 1 S
276341,118448,270,2005966,93-14700-24207,DIGITRON 35MM FLASH CAMERA DIGITRON CAMERA W/F...,DIGITRON 24 EXP FLASH CAMR

In [26]:
fasttext_model300 = api.load('fasttext-wiki-news-subwords-300')

NameError: name 'api' is not defined

In [ ]:
similarity_matrix = fasttext_model300.similarity_matrix(dictionary, tfidf=None, threshold=0.0, exponent=2.0, nonzero_limit=100)

In [ ]:
dct = pd.concat([df_analyse['DESC_BANK_ITEM_OLD'],df_analyse['DESC_BANK_ITEM_NAME']])
dct = dct.reset_index(drop=True)
dct

In [ ]:
documents = dct

In [ ]:
dictionary = corpora.Dictionary([simple_preprocess(doc) for doc in documents])

In [4]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [5]:
df_analyse = df_analyse[~(df_analyse['DESC_BANK_ITEM_NAME'].str.len()<=2)]
df_analyse = df_analyse[~(df_analyse['DESC_BANK_ITEM_OLD'].str.len()<=2)]

In [6]:
df_analyse['DESC_BANK_ITEM_OLD'] = df_analyse['DESC_BANK_ITEM_OLD'].astype(str)
df_analyse['DESC_BANK_ITEM_NAME'] = df_analyse['DESC_BANK_ITEM_NAME'].astype(str)

In [60]:
df_analyse[df_analyse['DESC_BANK_ITEM_NAME'].str.len()>200].to_csv("g200_chk.csv")

In [7]:
def listToString(s):  
    
    # initialize an empty string 
    str1 = " "  
    
    # traverse in the string   
    for ele in s: 
        ele = f'{ele}'+" "
        str1 += ele 
    
    # return string   
    return str1

class my_dictionary(dict): 
  
    # __init__ function 
    def __init__(self): 
        self = dict() 
          
    # Function to add key:value 
    def add(self, key, value): 
        self[key] = value 

import difflib
def closeMatches(patterns, word): 
     return difflib.get_close_matches(word, patterns)

In [8]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize
from jellyfish import soundex

In [17]:
#df_analyse.to_csv("df_analyse_02APR2021.csv",index=False)
#df_analyse.columns

In [13]:
import re
dict_obj_upc = my_dictionary()
dict_obj_tokenOld = my_dictionary()
dict_obj_tokenNew = my_dictionary()
dict_obj_tkn = my_dictionary()
dict_obj_tknold = my_dictionary()
dict_obj_cntry = my_dictionary()
allinone = []
#for upc in df_new_base['old_upc14'][(df_new_base['old_upc14'].isin(df_change_cnt['upc14']))==False]:#df_new_base['old_upc14']:#['10000314258','10000341569','10000325019','97018148892847']:
for upc in df_analyse.index:#['10000314258','10000341569','10000325019','97018148892847']:
    #print(upc)
    dict_obj_old = my_dictionary()
    dict_obj_new = my_dictionary()
    dict_obj_diff = my_dictionary()
    #.tolist() listToString()
    s = re.sub(r"[^a-z.A-Z0-9]+", ' ',df_analyse['DESC_BANK_ITEM_OLD'][upc])
    k = re.sub(r"[^a-z.A-Z0-9]+", ' ',df_analyse['DESC_BANK_ITEM_NAME'][upc])
    ln_cntry = df_analyse['COUNTRY_ID_OLD'][upc].item()
    #print(ln_cntry)
    X_list_old = word_tokenize(s)
    X_list_new = word_tokenize(k)

    ln_filtr_words = []
    ln_local_pattern = X_list_old
    for j in ln_local_pattern:
        ln_local = closeMatches(ln_local_pattern,j)
        if len(ln_local)>0:
            ln_filtr_words.append(ln_local[0])
        ln_local_pattern = [word for word in ln_local_pattern if word not in ln_local]
    X_list_old = ln_filtr_words
    for i in X_list_old:
        dict_obj_old.add(soundex(i),i)

    ln_filtr_words = []
    ln_local_pattern = X_list_new
    for j in ln_local_pattern:
        ln_local = closeMatches(ln_local_pattern,j)
        if len(ln_local)>0:
            ln_filtr_words.append(ln_local[0])
        ln_local_pattern = [word for word in ln_local_pattern if word not in ln_local]
    X_list_new = ln_filtr_words
    for i in X_list_new:
        dict_obj_new.add(soundex(i),i)
        
    ln_tokenOld = ''
    ln_tokenNew = ''
    for key in dict_obj_old.keys():
        if not key in dict_obj_new:
            dict_obj_diff.add(key,1)
            ln_tokenOld = ln_tokenOld + ' ' + dict_obj_old.get(key)
    for key in dict_obj_new.keys():
        if not key in dict_obj_old:
            ln_tokenNew = ln_tokenNew + ' ' + dict_obj_new.get(key)
            dict_obj_diff.add(key,1)
    allinone.append([df_analyse['SVI'][upc],len(word_tokenize(ln_tokenNew)),len(word_tokenize(ln_tokenOld)),ln_tokenNew,ln_tokenOld,len(dict_obj_new),ln_cntry])

In [43]:
#dfx

In [ ]:
import re
dict_obj_upc = my_dictionary()
dict_obj_tokenOld = my_dictionary()
dict_obj_tokenNew = my_dictionary()
dict_obj_tkn = my_dictionary()
dict_obj_tknold = my_dictionary()
dict_obj_cntry = my_dictionary()
allinone = []
#for upc in df_new_base['old_upc14'][(df_new_base['old_upc14'].isin(df_change_cnt['upc14']))==False]:#df_new_base['old_upc14']:#['10000314258','10000341569','10000325019','97018148892847']:
for upc in df_analyse.index:#['10000314258','10000341569','10000325019','97018148892847']:
    #print(upc)
    dict_obj_old = my_dictionary()
    dict_obj_new = my_dictionary()
    dict_obj_diff = my_dictionary()
    #.tolist() listToString()
    s = re.sub(r"[^a-z.A-Z0-9]+", ' ',df_analyse['DESC_BANK_ITEM_OLD'][upc])
    k = re.sub(r"[^a-z.A-Z0-9]+", ' ',df_analyse['DESC_BANK_ITEM_NAME'][upc])
    ln_cntry = df_analyse['COUNTRY_ID_OLD'][upc].item()
    #print(ln_cntry)
    X_list_old = word_tokenize(s)
    X_list_new = word_tokenize(k)

    ln_filtr_words = []
    ln_local_pattern = X_list_old
    for j in ln_local_pattern:
        ln_local = closeMatches(ln_local_pattern,j)
        if len(ln_local)>0:
            ln_filtr_words.append(ln_local[0])
        ln_local_pattern = [word for word in ln_local_pattern if word not in ln_local]
    X_list_old = ln_filtr_words
    for i in X_list_old:
        dict_obj_old.add(soundex(i),i)

    ln_filtr_words = []
    ln_local_pattern = X_list_new
    for j in ln_local_pattern:
        ln_local = closeMatches(ln_local_pattern,j)
        if len(ln_local)>0:
            ln_filtr_words.append(ln_local[0])
        ln_local_pattern = [word for word in ln_local_pattern if word not in ln_local]
    X_list_new = ln_filtr_words
    for i in X_list_new:
        dict_obj_new.add(soundex(i),i)
        
    ln_tokenOld = ''
    ln_tokenNew = ''
    for key in dict_obj_old.keys():
        if not key in dict_obj_new:
            dict_obj_diff.add(key,1)
            ln_tokenOld = ln_tokenOld + ' ' + dict_obj_old.get(key)
    for key in dict_obj_new.keys():
        if not key in dict_obj_old:
            ln_tokenNew = ln_tokenNew + ' ' + dict_obj_new.get(key)
            dict_obj_diff.add(key,1)
    allinone.append([df_analyse['COUNTRY_ID_OLD'][upc],df_analyse['KEYCAT_ID_OLD'][upc],df_analyse['BRAND_ID_OLD'][upc],
                     df_analyse['DESC_BANK_ITEM_OLD'][upc],df_analyse['DESC_BANK_ITEM_NAME'][upc],
                     df_analyse['SVI'][upc],len(word_tokenize(ln_tokenNew)),len(word_tokenize(ln_tokenOld)),
                     ln_tokenNew,ln_tokenOld,len(dict_obj_new),ln_cntry])

In [49]:
df_analyse.columns

Index(['COUNTRY_ID_OLD', 'KEYCAT_ID_OLD', 'BRAND_ID_OLD', 'SVI',
       'DESC_BANK_ITEM_OLD', 'COUNTRY_LOCATION_ID', 'KEYCAT_ID', 'BRAND_ID',
       'DESC_BANK_ITEM_NAME'],
      dtype='object')

In [48]:
dfx.columns

Index(['COUNTRY_ID_OLD', 'SVI', 'KEYCAT_ID_OLD', 'BRAND_ID_OLD', 'KEYCAT_ID',
       'BRAND_ID', 'DESC_BANK_ITEM_OLD', 'DESC_BANK_ITEM_NAME',
       'NEW_DESC_DIFF', 'OLD_DISC_DIFF', 'NEW_TOK_DIF', 'OLD_TOK_DIF',
       'TOT_NEW_TOKENS', 'TARGET'],
      dtype='object')

In [14]:
df_change_cnt = pd.DataFrame(allinone, columns=["upc14","NEW_TOK_DIF","OLD_TOK_DIF","NEW_DESC_DIFF","OLD_DISC_DIFF","TOT_NEW_TOKENS","CNTRY"])    
df_change_cnt = df_change_cnt[['CNTRY','upc14','NEW_DESC_DIFF','OLD_DISC_DIFF','NEW_TOK_DIF','OLD_TOK_DIF','TOT_NEW_TOKENS']]
df_change_cnt

,CNTRY,upc14,NEW_DESC_DIFF,OLD_DISC_DIFF,NEW_TOK_DIF,OLD_TOK_DIF,TOT_NEW_TOKENS
0,1,0-52200-576,OZ,4.0OZ BN S2 HMSTYL P B N SWPT POTO BCH NUT PO...,1,24,8
1,1,0-52200-576,BEECHNUT POTATO,BEECH NUT BABY FOOD POTATOES NATURALS CLASSIC...,2,12,8
2,1,0-52200-714,BNUT S2,BEECH NUT CLASSICS BABY FOOD STAGE 2 T BN TND...,2,16,5
3,1,0-52200-714,BNUT 0004.000,B NUT STAGE 2 4.00 OZ TENDER CARROT TZERE KER...,2,23,5
4,1,0-15000-4771,,4CT 3 GRADS BRRS GER GRD YGT MX 0000014OZ GB ...,0,27,5
...,...,...,...,...,...,...,...
278450,118448,76-5578-143,,MMRY 1PK,0,2,4
278451,118448,76-5578-191,MICRO,,1,0,6
278452,118448,76-5578-552,,1PK,0,1,5
278453,118448,27-1615-649,,SPEED EXP PACK GOLD X24 ZZZFILM 35MM III MAX ...,0,11,5
278454,118448,93-14700-24207,,35MM W 1PK,0,3,5

In [20]:
df_change_cnt.columns

Index(['CNTRY', 'upc14', 'NEW_DESC_DIFF', 'OLD_DISC_DIFF', 'NEW_TOK_DIF',
       'OLD_TOK_DIF', 'TOT_NEW_TOKENS'],
      dtype='object')

In [26]:
df_prd_an = df_analyse[['COUNTRY_ID_OLD', 'SVI', 'KEYCAT_ID_OLD', 'BRAND_ID_OLD', 'KEYCAT_ID', 'BRAND_ID',
       'DESC_BANK_ITEM_OLD', 'DESC_BANK_ITEM_NAME']].merge(df_change_cnt,left_on=['COUNTRY_ID_OLD', 'SVI'],
                                                          right_on=['CNTRY', 'upc14'],how='inner')
#.drop_duplicates(keep='first').to_csv("Data_moreMerge_02APR2021.csv",index=False)

In [28]:
df_prd_an['TARGET']=0
df_prd_an.loc[((df_prd_an['KEYCAT_ID_OLD'] != df_prd_an['KEYCAT_ID']) | (df_prd_an['BRAND_ID_OLD'] != df_prd_an['BRAND_ID'])),'TARGET']=1

In [32]:
df_prd_an[['COUNTRY_ID_OLD', 'SVI', 'KEYCAT_ID_OLD', 'BRAND_ID_OLD', 'KEYCAT_ID',
       'BRAND_ID', 'DESC_BANK_ITEM_OLD', 'DESC_BANK_ITEM_NAME',
       'NEW_DESC_DIFF', 'OLD_DISC_DIFF', 'NEW_TOK_DIF', 'OLD_TOK_DIF',
       'TOT_NEW_TOKENS', 'TARGET']].to_csv("Combined_Desc_Data.csv",index=False)

In [15]:
df_change_cnt.to_csv("df_change_cnt.csv",index=False)

In [74]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\opc\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [55]:
import gensim
# upgrade gensim if you can't import softcossim
from gensim.matutils import softcossim 
from gensim import corpora
import gensim.downloader as api
from gensim.utils import simple_preprocess
print(gensim.__version__)
df_analyse['COS_SIMILAR'] = df_analyse.apply(lambda x: softcossim(dictionary.doc2bow(simple_preprocess(str(x.DESC_BANK_ITEM_OLD))),
                        dictionary.doc2bow(simple_preprocess(str(x.DESC_BANK_ITEM_NAME))),similarity_matrix ),axis=1)

3.8.3

IndexError: index (213727) out of range

In [ ]:
df_analyse

In [ ]:
from fuzzywuzzy import fuzz
def fuzzymatch(x,y):
    #x = x.str.lower()
    #y = y.str.lower()
    z = fuzz.token_sort_ratio(x,y)
    return z

In [16]:
df_analyse.columns

Index(['COUNTRY_LOCATION_ID', 'KEYCAT_ID', 'BRAND_ID', 'SVI',
       'DESC_BANK_ITEM_OLD', 'DESC_BANK_ITEM_NAME', 'COS_SIMILAR'],
      dtype='object')

In [ ]:
df_analyse['FUZ_SIMILAR']=0
df_analyse['FUZ_SIMILAR'] = df_analyse.apply(lambda x: fuzzymatch(str(x['DESC_BANK_ITEM_OLD']),str(x['DESC_BANK_ITEM_NAME'])),axis=1)

In [ ]:
df_analyse

In [19]:
df_analyse[df_analyse['']]

Index(['COUNTRY_LOCATION_ID', 'KEYCAT_ID', 'BRAND_ID', 'SVI',
       'DESC_BANK_ITEM_OLD', 'DESC_BANK_ITEM_NAME', 'COS_SIMILAR',
       'FUZ_SIMILAR'],
      dtype='object')